In [ ]:
import numpy as np

empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)

ones_array = np.ones((4, 2))
print("\nAll Ones Array (4x2):\n", ones_array)

full_array = np.full((3, 3), 7)
print("\nFull Array (3x3 filled with 7):\n", full_array)

given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros Like Given Array:\n", zeros_like_array)

ones_like_array = np.ones_like(given_array)
print("\nOnes Like Given Array:\n", ones_like_array)

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:\n", numpy_array)


Empty Array (2x2):
 [[4.42350137e-315 0.00000000e+000]
 [6.90763325e-310 6.90763311e-310]]

All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full Array (3x3 filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Given Array:
 [[0 0]
 [0 0]]

Ones Like Given Array:
 [[1 1]
 [1 1]]

Converted NumPy Array:
 [1 2 3 4]


In [ ]:
import numpy as np

array1 = np.arange(10, 50)
print("Array from 10 to 49:\n", array1)

matrix3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix (0 to 8):\n", matrix3x3)

identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of size 30:\n", random_array)
print("Mean of array:", mean_value)

random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Random Array:\n", random_10x10)
print("Min value:", min_value, "Max value:", max_value)

zero_array = np.zeros(10)
zero_array[4] = 1  # index starts from 0
print("\nZero array with 5th element as 1:\n", zero_array)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:\n", reversed_arr)

border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D array with 1 on border and 0 inside:\n", border_array)

checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard pattern:\n", checkerboard)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix (0 to 8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30:
 [0.27053661 0.24075073 0.67480862 0.65948033 0.16826259 0.38648206
 0.06173299 0.52883686 0.12721208 0.44363005 0.23166013 0.54589261
 0.40901844 0.15832278 0.59804115 0.17091247 0.74415298 0.25539799
 0.9845702  0.34039162 0.52907355 0.95973637 0.3534269  0.05155982
 0.33375446 0.2161763  0.49712601 0.67917659 0.49266089 0.89904193]
Mean of array: 0.43372753644890627

10x10 Random Array:
 [[0.62096551 0.85334723 0.99258728 0.23264749 0.98821417 0.55711778
  0.86514207 0.55041679 0.87386397 0.28259523]
 [0.50730876 0.51371324 0.38044036 0.87081183 0.37015544 0.78300032
  0.4814742  0.30080217 0.73601497 0.43120807]
 [0.85007235 0.58694228 0.78739756 0.7698229  0.05705557 0.79459117
  0.30392183 0.14232527 0.

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("x + y:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\nx - y:\n", sub_xy)

# 3. Multiply the array with an integer (e.g., 3)
mult_x = x * 3
print("\nx * 3:\n", mult_x)

# 4. Find the square of each element of the array
square_x = x ** 2
print("\nx squared:\n", square_x)

# 5. Dot product
dot_vw = np.dot(v, w)        # dot product of vectors
dot_xv = np.dot(x, v)        # dot product of matrix and vector
dot_xy = np.dot(x, y)        # dot product of matrices

print("\nDot product v.w:", dot_vw)
print("Dot product x.v:\n", dot_xv)
print("Dot product x.y:\n", dot_xy)

# 6. Concatenate arrays
concat_row_xy = np.concatenate((x, y), axis=0)   # along rows
concat_col_vw = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)  # along columns

print("\nConcatenate x and y along rows:\n", concat_row_xy)
print("Concatenate v and w along columns:\n", concat_col_vw)

# 7. Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenate x and v:\n", concat_xv)
except ValueError as e:
    print("\nError concatenating x and v:", e)
    print("Explanation: x is a 2x2 matrix and v is a 1D array of length 2. Dimensions do not match along axis=1 for row-wise concatenation, hence it throws an error.")


x + y:
 [[ 6  8]
 [10 13]]

x - y:
 [[-4 -4]
 [-4 -3]]

x * 3:
 [[ 3  6]
 [ 9 15]]

x squared:
 [[ 1  4]
 [ 9 25]]

Dot product v.w: 219
Dot product x.v:
 [29 77]
Dot product x.y:
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]

Error concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is a 2x2 matrix and v is a 1D array of length 2. Dimensions do not match along axis=1 for row-wise concatenation, hence it throws an error.


In [ ]:
import numpy as np

# ----------------------
# Given Arrays
# ----------------------
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# ----------------------
# 1. Prove A × A⁻¹ = I
# ----------------------
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("1. A × A⁻¹:\n", identity_check)

# ----------------------
# 2. Prove AB ≠ BA
# ----------------------
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("BA:\n", BA)
print("AB equal to BA?", np.array_equal(AB, BA))

# ----------------------
# 3. Prove (AB)ᵀ = BᵀAᵀ
# ----------------------
AB_transpose = (np.dot(A, B)).T
BT_AT = np.dot(B.T, A.T)
print("\n3. (AB)ᵀ:\n", AB_transpose)
print("BᵀAᵀ:\n", BT_AT)
print("Are they equal?", np.array_equal(AB_transpose, BT_AT))

# ----------------------
# 4. Solve linear equations using inverse
# Equations:
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9
# ----------------------
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Using inverse
A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)
print("\n4. Solution using inverse [x, y, z]:", X)

# ----------------------
# Optional: Solve using np.linalg.solve (more efficient)
# ----------------------
X_solve = np.linalg.solve(A_eq, B_eq)
print("Solution using np.linalg.solve [x, y, z]:", X_solve)


1. A × A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB equal to BA? False

3. (AB)ᵀ:
 [[23 51]
 [13 29]]
BᵀAᵀ:
 [[23 51]
 [13 29]]
Are they equal? True

4. Solution using inverse [x, y, z]: [ 2.  1. -2.]
Solution using np.linalg.solve [x, y, z]: [ 2.  1. -2.]
